image: "python:2.7"
before_script:
  - pip install tox

tests:2.7:
  script:
    - tox -r -e py27
tests:3.4:
  image: "python:3.4"
  script:
    - tox -r -e py34
flake8:
  script:
    - tox -e flake8
