tests:2.7:
  image: "python:2.7"
  before_script:
    - pip install tox
    - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh
    - bash Miniconda2-latest-Linux-x86_64.sh -b -p ~/miniconda2
    - rm Miniconda2-latest-Linux-x86_64.sh
    - export PATH="~/miniconda2/bin:$PATH"
    - conda config --add channels bioconda
    - conda install samtools
    - conda install bowtie2
    - export PATH="/root/miniconda2/samtools:$PATH"
    - export PATH="/root/miniconda2/bowtie2:$PATH"
  script:
    - tox -r -e py27
tests:3.4:
  image: "python:3.4"
  before_script:
    - pip install tox
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
    - bash Miniconda3-latest-Linux-x86_64.sh -b -p ~/miniconda3
    - rm Miniconda3-latest-Linux-x86_64.sh
    - export PATH="~/miniconda3/bin:$PATH"
    - conda config --add channels bioconda
    - conda install samtools
    - conda install bowtie2
    - export PATH="/root/miniconda2/samtools:$PATH"
    - export PATH="/root/miniconda2/bowtie2:$PATH"
  script:
    - tox -r -e py34
flake8:
  image: "python:2.7"
  before_script:
    - pip install tox
  script:
    - tox -e flake8
