tests:2.7:
  image: "python:2.7"
  before_script:
    - pip install tox
    - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh
    - bash Miniconda2-latest-Linux-x86_64.sh -b -p ~/miniconda2
    - rm Miniconda2-latest-Linux-x86_64.sh
    - export PATH="~/miniconda2/bin:$PATH"
    - hash -r
    - conda config --add channels bioconda
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda create -q -n test-environment python=2.7 samtools=0.1.19 bowtie2
    - source activate test-environment
  script:
    - tox -r -e py27
tests:3.4:
  image: "python:3.4"
  before_script:
    - pip install tox
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
    - bash Miniconda3-latest-Linux-x86_64.sh -b -p ~/miniconda3
    - rm Miniconda3-latest-Linux-x86_64.sh
    - export PATH="~/miniconda3/bin:$PATH"
    - hash -r
    - conda config --add channels bioconda
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda create -q -n test-environment-py3 python=3.4 samtools=0.1.19 bowtie2
    - source activate test-environment-py3
  script:
    - /usr/local/bin/python -m virtualenv --python /root/miniconda3/envs/test-environment-py3/bin/python3.4 py34
    - tox -r -e py34
flake8:
  image: "python:2.7"
  before_script:
    - pip install tox
  script:
    - tox -e flake8
